NET "sysclk" LOC = "C9" ;
NET "btn" LOC = "H13" | IOSTANDARD = LVTTL | PULLDOWN ;
NET "sw1" LOC = "L13" | IOSTANDARD = LVTTL | PULLUP ;
NET "sw2" LOC = "L14" | IOSTANDARD = LVTTL | PULLUP ;
NET "sw3" LOC = "H18" | IOSTANDARD = LVTTL | PULLUP ;
NET "sw4" LOC = "N17" | IOSTANDARD = LVTTL | PULLUP ;
